docs: improve documentation
jeremychia/singapore-parliament-speeches-dbt pull request #31
Opened 2024-08-11 13:30 UTC by jeremychia

this PR aims to:

* revise existing docstrings for brevity
* include missing descriptions for columns
* revise existing models to minimally include information on:
  * what can i find in here?
  * what does each row represent?
* include missing descriptions for models

2024-08-15 13:06 UTC, roycehoe requested changes, later dismissed
praise: thanks for raising this PR. Honestly, most of my comments are nitpicks. Other than that, I think the documentation is much better now :)

side note. I'm currently trying out writing comments using this format:
https://conventionalcomments.org/

I quite like it and will probably stick with this format

2024-08-15 13:06 UTC, roycehoe commented on docs/models/models_members.md
> +Each row represents one model.
*one member of parliament

else, elaborate what "model" means

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/bill_day_diff_first_second_reading.md
> +Difference between first_reading_date and second_reading_date.
suggestion: Please include unit of measure (in this case, days)

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/bill_day_diff_second_third_reading.md
> +Difference between second_reading_date and third_reading_date (usually 0).
suggestion: Refer to above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/bill_day_diff_third_reading_passed.md
> +Difference between third_reading_date and passed_date.
suggestion: Refer to above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/bill_first_reading_date.md
> +Date bill was first introduced to parliament. Members will thereafter have time to read the bill.
suggestion: Include date format

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/bill_passed_date.md
> +Date bill was passed in parliament. Thereafter, needs President's Assent to become law.
suggestion: See above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/bill_second_reading_date.md
> +Date bill was subsequently introduced to parliament. This is typically when it is debated and/or amendments are proposed.
nitpick: Missing "The" at start of sentence

suggestion: specify date format

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/bill_third_reading_date.md
> +Date bill was read for the third time to parliament. This is typically when there are amendments.
suggestion: refer above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/count_sentences.md
> +Number of sentences within a given speech. These are detected by periods, question marks, exclamation marks.
suggestion:

"Number of sentences in a given speech, where sentences are defined as continuous blocks of text ending with periods, question marks, or exclamation marks."

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/datetime.md
> +When a parliamentary sitting commenced for a given day.
suggestion: specify time format

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/effective_from_date.md
> +Date which the appointment is effective from.
suggestion: see above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/effective_to_date.md
> +Date which the appointment is effective to.
suggestion: see above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/is_latest_position.md
> +True for latest position.
suggestion: "Boolean value. True if the MP is currently holding this appointment, or if this was the last appointment the MP held before stepping down. False otherwise."

suggestion: Try to standardize the description to start with the data type

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/is_long_speech.md
> +TRUE if the word count is at or above the 90th percentile of all speeches.
suggestion: see above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/is_present.md
> +TRUE if member was present for that day's sitting.
suggestion: see above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/is_primary_question.md
> +TRUE if was a parliamentary question posed.
suggestion: see above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/is_short_speech.md
> +TRUE if the word count is at or below the 10th percentile of all speeches.
suggestion: see above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/is_topic_constitutional.md
> +TRUE if topic concerns a constitution amendment.
suggestion: see above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/is_topic_procedural.md
> +TRUE if topic concerns a procedural statement, and therefore should be considered excluded from the speech count.
suggestion: see above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/is_vernacular_speech.md
> +TRUE if speeches contains phrase "vernacular speech".
suggestion: see above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/member_count_sittings_present.md
> +Number of sittings the member attended (was present for).
nitpick: redundant comment in brackets. By definition, if you attend a session, you are present

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/member_count_sittings_spoken.md
> +Number of parliamentary sittings during which the member made a speech/asked a question.
nitpick: Don't use "/". Use "or" instead for standardization purposes; the use of "/" isn't used anywhere else in this documentation

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/member_name_website.md
> +MP's name for parliament's website
question: should this be "from" instead of "for"

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/ministry_addressed.md
> +Ministry which question was addressed to. Derived from which minister the question was addressed to.
nitpick: use a comma or semi-colon to delimit these two phrases, given their close relation to each other

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/speech_order.md
> +Denotes the sequence or order in which the speech was delivered during the sitting.
nitpick: Simply write this as "Order in which the speech was delivered during the sitting.". Everything else is redundant

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/speech_text.md
> +Contains the actual content of the speech delivered in Parliament.
suggestion: "Raw content"

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/topic_order.md
> +Denotes the sequence or order in which the topic was debated during the sitting.
suggestion: refer above

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/topic_type.md
> +Indicates the type of section associated with the topic.
suggestion: "Section type associated with the topic."

2024-08-15 13:06 UTC, roycehoe commented on docs/columns/vernacular_speech_language.md
> +Specifies the language of the vernacular speech.
suggestion: Start sentence with "language" (which can be considered a "language" datatype by means of an enum)

2024-08-16 14:13 UTC, jeremychia commented on docs/columns/member_name_website.md
> +MP's name for parliament's website
it was meant to be 'for', as it's the ID used to locate the subpage for the member

2024-08-16 14:15 UTC, jeremychia commented on docs/columns/speech_text.md
> +Contains the actual content of the speech delivered in Parliament.
replaced "actual" with "raw"

2024-08-16 14:16 UTC, jeremychia commented on docs/columns/topic_order.md
> +Denotes the sequence or order in which the topic was debated during the sitting.
removed "denotes the sequence"

2024-08-16 19:01 UTC, merged

2024-08-17 01:01 UTC, roycehoe commented on docs/columns/bill_day_diff_first_second_reading.md
> +Difference between first_reading_date and second_reading_date.
suggestion: difference between 2 dates could be represented in seconds, minutes, or days. Do mention the unit of measurement.

2024-08-17 01:03 UTC, roycehoe commented on docs/columns/bill_first_reading_date.md
> +Date bill was first introduced to parliament. Members will thereafter have time to read the bill.
suggestion: date format is (dd/mm/yyyy), (mm/dd/yyyy) etc. please specify